name = "naya-portfolio"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-01"
pages_build_output_dir = ".vercel/output/static"

[vars]
ADMIN_USERNAME = "admin"
R2_ENDPOINT = "https://fe19d3afc8180ebd5792c34afb1f85af.r2.cloudflarestorage.com"
R2_BUCKET_NAME = "naya-assets"
NEXT_PUBLIC_R2_PUBLIC_URL = "https://pub-49f6712bf69144dbb92c254052a438e3.r2.dev"

[[d1_databases]]
binding = "DB"
database_name = "naya-db"
database_id = "6e8bde04-e7e1-4e4f-a725-c18cd54b3ff4"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "naya-assets"
